tasks:
  - name: Install dependencies and start Expo
    init: npm install
    command: npx expo start --tunnel

ports:
  - port: 19000
    onOpen: ignore
  - port: 19001
    onOpen: ignore
  - port: 19002
    onOpen: open-preview